### ISSUE TITLE
'Assertion failed' error when running realizability checking

### ISSUE THREAD

**Issue by andreaskatis** [kind2-mc/kind2#1118]
[vehicleSpec_121124.lus.txt](https://github.com/user-attachments/files/18102966/vehicleSpec_121124.lus.txt)

Realizability checking fails for the attached file, with the following error:

`<Error> Error opening input file 'vehicleSpec.lus':
        File "src/lustre/lustreAstNormalizer.ml", line 106, characters 4-10: Assertion failed
`

This happens when using the latest release (v2.2.0). Downgrading to Kind v2.1.1 seems to resolve the problem.

Best Regards,

Andreas

**Comment by daniel-larraz** [comment]
Thank you for reporting this issue. As a workaround until the issue is fixed, you can pass `--check_environment false` to Kind 2.
