### ISSUE TITLE
Feature request: nested record access

### ISSUE THREAD

**Issue by agacek** [kind2-mc/kind2#122]
For the AGREE tool we are generating Lustre with nested records. Based on kind2 outout and browsing the Lustre grammar, it looks like kind2 does not yet supported nested record access. For example, the following file generates a parser error:

    type point = struct { x : int; y : int };
    type weighted_point = struct { weight : real; p : point };
    
    node main(wp : weighted_point) returns (sum : int);
    let
      sum = wp.p.x + wp.p.y;
    tel;

Yields

    Parser error in line 6 col. 12: Syntax error

**Comment by agacek** [comment]
John Backes said this issue has been fixed. Is that true?

**Comment by AdrienChampion** [comment]
Version 0.8 does not support it, but the [contracts and arrays branch][contracts] (which will soon become the *official* develop branch) does.

[contracts]: https://github.com/kind2-mc/kind2/tree/contracts-and-arrays (contracts-and-arrays branch)

**Comment by AdrienChampion** [comment]
The contracts and arrays branch has become the *official* develop branch, closing issue.
