### ISSUE TITLE
Forward references not allowed

### ISSUE THREAD

**Issue by agacek** [kind2-mc/kind2#126]
Kind 2 does not allow forward references such as in these examples:

```
type t1 = struct { x : t2 };
type t2 = int;
```

```
const c1 = c2;
const c2 = 1;
```

```
node main() returns (ok : bool);
let
  ok = other();
tel;

node other() returns (ok : bool);
let
  ok = true;
tel;
```

From [this Lustre manual](http://www.pps.univ-paris-diderot.fr/~dogguy/files/progsyn/manual_lustre.pdf):

> Four kinds of objects can be declared: [Constants, Types, Functions, Nodes]. The order of these declarations is meaningless. All the declared objects are global to the program. (Page 15)

> Types can be declared in any order. (Page 24)

> Constants can be declared in any order. (Page 30)

> Nodes can be declared in any order. (Page 35)

Moreover, when generating Lustre files it is often inconvenient to have to topologically sort all types, constants, and nodes. It would be great if Kind 2 could be extended to allow arbitrary order of definitions.

**Comment by agacek** [comment]
What is the current status of this? Can types, constants, and nodes be declared in any order?

**Comment by AdrienChampion** [comment]
Kind 2 0.8 supports forward references for nodes and constants.
Not types though.

**Comment by AdrienChampion** [comment]
As of https://github.com/kind2-mc/kind2/commit/2d74a24d3ace8ec95f107ee5c81c30bfbfdf2223, Kind 2 supports forwards references for nodes, types, contracts and constants.
