### ISSUE TITLE
Build failure in czmq

### ISSUE THREAD

**Issue by LeoTestard** [kind2-mc/kind2#342]
The develop branch fails to build on Debian sid because of the use of the deprecated macro _BSD_SOURCE in czmq:

```
In file included from /usr/include/ctype.h:25:0,
                 from ../include/czmq_prelude.h:203,
                 from ../include/czmq.h:19,
                 from zauth.c:25:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^
cc1: all warnings being treated as errors
```

This has been fixed upstream in czmq so it's just a matter of updating.

**Comment by AdrienChampion** [comment]
Hi Leo,

Thanks for pointing that out.

We're in the process of [updating our ocaml wrapper to czmq 3.0.2][PR].
The develop branch should soon be updated accordingly.
We'll let you know as soon as it is.

[PR]: https://github.com/chsticksel/ocamlczmq/pull/14 (ocamlczmq PR 14)

**Comment by AdrienChampion** [comment]
Hi Leo,

We updated the ocaml wrapper for czmq, see [PR 348][PR348].
Sorry it took so long, but it's trickier than it seems :)

Let us know if the develop branch works for you now.

[PR348]: https://github.com/kind2-mc/kind2/pull/348 (PR 348)

**Comment by AdrienChampion** [comment]
I'll close this for now as it seems fixed. @LeoTestard let us know if this works for you, reopen this issue if it doesn't.
