### ISSUE TITLE
Array dimensions reversed

### ISSUE THREAD

**Issue by agacek** [kind2-mc/kind2#368]
Kind 2 treats the the declaration `int^3^2` as an array of size 3 each of whose elements are arrays of size 2. This is backwards from Lustre and SCADE.

cf. Scade Language Primer, Section 5.3, Multidimensional Operators:

> Array types are unidimensional: it is not possible in Scade to directly define
> multidimensional arrays. A matrix is encoded by an array of arrays, as in:
> `type SpaceLinearMorphism = real ^ 4 ^ 6 ;`
> `mat : SpaceLinearMorphism ;`
> This defines a matrix of six arrays of four elements each. Selecting an element in this array
> by the expression `mat[i][j]` first checks whether `i` belongs to interval `[0..5]` then that `j`
> belongs to `[0..3]`. Notice the order of index declaration is the reverse from the
> one used for selection.

**Comment by mebsout** [comment]
Thanks for the bug report. I've fixed it in the arrays branch.
