### ISSUE TITLE
How to define pkg-config macros for kind2

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#457]
==> ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /opt/local/bin/aclocal -I config --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /opt/local/bin/autoconf --include=config --force
configure.ac:52: error: missing some pkg-config macros (pkg-config package)
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:61: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:62: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:426: error: missing some pkg-config macros (pkg-config package)
configure:5403: error: possibly undefined macro: AC_DISABLE_STATIC
configure:5407: error: possibly undefined macro: AC_ENABLE_STATIC
autoreconf: /opt/local/bin/autoconf failed with exit status: 1
autogen.sh: error: autoreconf exited with status 0
./autogen.sh: line 10: pushd: czmq: No such file or directory
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /opt/local/bin/aclocal -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /opt/local/bin/autoconf
configure.ac:52: error: missing some pkg-config macros (pkg-config package)
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:61: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
configure.ac:62: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:426: error: missing some pkg-config macros (pkg-config package)
configure:5403: error: possibly undefined macro: AC_DISABLE_STATIC
configure:5407: error: possibly undefined macro: AC_ENABLE_STATIC
autoreconf: /opt/local/bin/autoconf failed with exit status: 1
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: /opt/local/bin/aclocal
autoreconf: configure.ac: tracing
autoreconf: configure.ac: adding subdirectory libzmq to autoreconf
autoreconf: Entering directory `libzmq'
autoreconf: running: /opt/local/bin/aclocal -I config
autoreconf: configure.ac: not using Libtool
autoreconf: running: /opt/local/bin/autoconf
autoreconf: running: /opt/local/bin/autoheader
autoreconf: running: /opt/local/bin/automake --no-force
configure.ac:46: error: required file 'config/compile' not found
configure.ac:46:   'automake --add-missing' can install 'compile'
configure.ac:60: error: required file 'config/config.guess' not found
configure.ac:60:   'automake --add-missing' can install 'config.guess'
configure.ac:60: error: required file 'config/config.sub' not found
configure.ac:60:   'automake --add-missing' can install 'config.sub'
configure.ac:14: error: required file 'config/install-sh' not found
configure.ac:14:   'automake --add-missing' can install 'install-sh'
configure.ac:14: error: required file 'config/missing' not found
configure.ac:14:   'automake --add-missing' can install 'missing'
Makefile.am:16: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:16:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:16:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:16:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:16:   its definition is in aclocal's search path.
Makefile.am: error: required file 'config/depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
parallel-tests: error: required file 'config/test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
autoreconf: /opt/local/bin/automake failed with exit status: 1

**Comment by daniel-larraz** [comment]
Hello,
Could you check if GNU Libtool is installed on your system, please?

In Debian-based distributions, you can install it with:
sudo apt-get install libtool

Thank you,
Daniel

**Comment by hbourbouh** [comment]
Hi Daniel,
I have  libtool-2.4.6_1 installed I tried to reinstall it using Homebrew, I am using Mac
The error is still the same

Thanks,
Hamza

**Comment by daniel-larraz** [comment]
Hi Hamza,

It looks like autoreconf cannot find Libtool in your PATH.

I noticed from your output that aclocal and autoconf are found in /opt/local/bin, which is not the standard location used by Homebrew (/usr/local).

Could it be, by any chance, that you didn't install aclocal and autoconf using Homebrew? Some things may not build when installed elsewhere.

Please, check your PATH and the installation directory of Libtool.

Daniel

**Comment by hbourbouh** [comment]
It is solved Thanks 👍 
I installed autoconf and automake with brew, libtool was already installed by homebrew.
