### ISSUE TITLE
docker run command

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#464]
Hi Daniel,

I face this error using docker on Centos 6.9

docker run -v /data/software/cocoTeam/demo2/models_with_properties/lustre_files/src_tcm_with_properties_PP:/lus kind2/kind2:dev -xml --timeout 60.0  --lus_main tcm_with_properties_PP_TCM_Longitudinal_Guide_130  /lus/tcm_with_properties_PP.lus
<?xml version="1.0"?>
<Results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" enabled="bmc,ind,ind2,ic3,invgents,invgenos,invgenintos,invgenintos" timeout="60.000000" bmc_max="0" compositional="false" modular="false">

<Log class="info" source="parse">kind2 v1.1.0</Log>
<Log class="fatal" source="parse">
  Error opening input file "/lus/tcm_with_properties_PP.lus":
  Sys_error("/lus/tcm_with_properties_PP.lus: No such file or directory")
</Log>

</Results>

Normally the file tcm_with_properties_PP.lus does exist in /data/software/cocoTeam/demo2/models_with_properties/lustre_files/src_tcm_with_properties_PP repo

Do you have any idea?

Thanks
Hamza

**Comment by daniel-larraz** [comment]
Hi Hamza,

I cannot reproduce the issue. The command should work. 

Best,
Daniel

**Comment by hbourbouh** [comment]
Hi Daniel,

Could you tell me how to run the bash on your image?
doing this docker run -t -i kind2/kind2:dev /bin/sh
is not working, it runs kind2 on /bin/sh :)

Thanks

Hamza

**Comment by daniel-larraz** [comment]
Hi Hamza,

The Kind2 image uses an ENTRYPOINT instruction to set the main command. You can override it using the docker run --entrypoint flag.

`docker run --entrypoint /bin/sh -t -i kind2/kind2:dev`

Best,
Daniel

**Comment by hbourbouh** [comment]
Nice Thanks
