### ISSUE TITLE
docker build -t kind2-local .

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#465]
Hi Daniel

I got this error runing : docker build -t kind2-local .
Step 30/41 : RUN ./latest_proof_cvc4.sh
 ---> Running in 764db9b71eb1
--2017-04-18 00:29:15--  http://cvc4.cs.nyu.edu/cvc4-builds/x86_64-linux-opt-proofs/unstable/
Resolving cvc4.cs.nyu.edu (cvc4.cs.nyu.edu)... 128.122.49.30
Connecting to cvc4.cs.nyu.edu (cvc4.cs.nyu.edu)|128.122.49.30|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://cvc4.cs.stanford.edu/ [following]
--2017-04-18 00:29:16--  http://cvc4.cs.stanford.edu/
Resolving cvc4.cs.stanford.edu (cvc4.cs.stanford.edu)... 171.64.78.10
Connecting to cvc4.cs.stanford.edu (cvc4.cs.stanford.edu)|171.64.78.10|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://cvc4.cs.stanford.edu/web/ [following]
--2017-04-18 00:29:17--  http://cvc4.cs.stanford.edu/web/
Reusing existing connection to cvc4.cs.stanford.edu:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index'

     0K .......... .......... ....                              244K=0.1s

2017-04-18 00:29:17 (244 KB/s) - 'index' saved [24647]

could not retrieve latest cvc4 version
The command '/bin/sh -c ./latest_proof_cvc4.sh' returned a non-zero code: 2

**Comment by daniel-larraz** [comment]
Hi Hamza,

The URL for downloading the latest version of CVC4 has changed. I'll fix it.

Thanks,
Daniel
