### ISSUE TITLE
Kind2 Docker

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#468]
Hi Daniel,

Is it normal That Kind2 gives different result for different executions, It gives me Unknown and sometimes a Counter Example.
I know that it depends on which solver it uses, so in case if we don't fix the solver, is it not deterministic? 

PS: I am using the docker version, I tried also to rebuild it from the last version of kind2 in develop branch.

Thanks

Hamza

**Comment by daniel-larraz** [comment]
Hi Hamza,

Using different solvers is certainly a source of nondeterministic behavior, but it is not the only one. Kind2 executes multiple engines in parallel, and they share information that can affect each other. Moreover, slight changes in the input given to an SMT solver can influence how the solver searches for a solution. These SMT inputs depend on the original system, but also on the intermediate solutions found during the execution.

Best,
Daniel
