### ISSUE TITLE
 Illegal unguarded pre under a node call in this contract

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#491]
Hi,

I am trying to use compositional verification on the attached example. I tried garantee and mode version. I keep getting " Illegal unguarded pre under a node call in this contract" error
where I can not trace and understand.

Thanks in advance
Hamza
[two_counters.txt](https://github.com/kind2-mc/kind2/files/1363669/two_counters.txt)

**Comment by backesj** [comment]
Hi Bourbouh,

My guess is that your problem is likely with this node:

node intloopcounter_mutant (x: bool) returns (out: bool)

var __intloopcounter_3: bool;
    __intloopcounter_2: int;
    __intloopcounter_1: bool;
    time: int;
let

       time = (if __intloopcounter_1 then 0 else
               (if __intloopcounter_3 then 0 else (__intloopcounter_2 +
1)));
       __intloopcounter_3 = (__intloopcounter_2 >= 3);
       __intloopcounter_2 = pre time;
       __intloopcounter_1 = (true -> false);
       out = (time = 2);
tel


Specifically, the following variable assignment:

       __intloopcounter_2 = pre time;

Here you reference the previous value of the variable "time", but you do
not guard it with an arrow expression.  You use this node in the contract
for the node "intloopcounter" so that is probably why you are getting this
error.

- John

**Comment by hbourbouh** [comment]
Thanks, That was a code generated automatically, do you have an idea how to solve the issue without touching the code. Does kind2 have an option to ignore such errors.
Thanks

**Comment by backesj** [comment]
I'm not sure, but you should change whatever code generator this came from.
Depending on what your semantics are for lustre an unguarded pre either
returns a non-deterministic value or causes undefined behavior. This
expression should really be guarded.

- John

**Comment by hbourbouh** [comment]
This is a normalized code, In fact we are sure it is always guarded.
If you see the use of such variables are always in IF statement.
time = (if __intloopcounter_1 then 0 else __intloopcounter_2;)
where  __intloopcounter_1 = (true -> false); gives if it is the initial step.

**Comment by backesj** [comment]
It is not guarded in the contract for node "intloopcounter ":

node intloopcounter (x:bool) returns (out:bool);
(*@contract
mode equal (
  require true;
  ensure  out = intloopcounter_mutant (x);
);
*)
var time: int;
let
  time = 0 -> if pre(time) = 3 then 0
            else pre(time) + 1;
  out = (time = 2);
tel

**Comment by daniel-larraz** [comment]
Since Kind 2 runs in a non-strict mode by default (--lus_strict false), I [changed](https://github.com/kind2-mc/kind2/commit/75940fbe7f84cf40db746e689ab1b16c25a9e7b7) the error messages to warnings. That should fix this issue.
