### ISSUE TITLE
Runtime error in invariant manager

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#558]
Hi Daniel,
Using the last version of Kind2 in develop branch I get this error very often today.
kind2 v1.1.0-283-g270c506c
</Property>
<Log class="fatal" source="parse">
  Runtime error in invariant manager: Not_found
</Log>
Do you know what may cause it?

Thanks

**Comment by daniel-larraz** [comment]
Hi Hamza,

I don't know the cause. Unfortunately, the error message is very generic.

Can you send me a Lustre model to reproduce the issue?

Thanks.

**Comment by ploc** [comment]
We don't really understand why but looking at running processes, lots (like a very very large set) of z3 processes are still running. We also have kind2 processes active while the main one is finished. May be when we have too much os these processes we obtain this fork issue. The solution is to kill the remaining  z3 and kind2.

**Comment by daniel-larraz** [comment]
#582 should fix this issue

**Comment by imedBennour** [comment]
Hi Daniel

I got the   same  error: <Error> Runtime error in invariant manager: Not_found
Please find attached the Lustre model.

Best regards

[Modem_allCycles_integer.lus.zip](https://github.com/kind2-mc/kind2/files/5219753/Modem_allCycles_integer.lus.zip)

**Comment by daniel-larraz** [comment]
Hello,

Could you please share some details about your environment?
Operating System, Kind 2 version (`kind2 --version`), SMT solver and version.

Thanks,
Daniel

**Comment by imedBennour** [comment]
Hi  Daniel

I'am using the  Docker framework. I tested the two versions of kind2 using:
 docker pull kind2/kind2:dev
 docker pull kind2/kind2

Also tested  on  two OS:
-Ubuntu 16.04.7 LTS
- and suse  18

i7 machine with 8 GB of RAM

The docker version is :
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Thu Aug 15 15:12:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false


Best regards
--
Imed  E.  BENNOUR
 Prof. Ecole Nationale d’Ingénieurs de Sousse (ENISo)




Le lun. 14 sept. 2020 à 17:47, Daniel Larraz <notifications@github.com> a
écrit :

**Comment by imedBennour** [comment]
Hello

After some tests, I found out that the error occurs only with the Docker
use.

Best regards
--
Imed  E.  BENNOUR
 Ecole Nationale d’Ingénieurs de Sousse (ENISo)
