### ISSUE TITLE
BMC Unrolling of the system is unsat at 1, the system has no more reachable states.

### ISSUE THREAD

**Issue by anmavrid** [kind2-mc/kind2#560]
Hi,
I used the stopwatch example from the Kind2 web interface. I modified the code in order to remove the implementation of node stopWatch and use explicit traces instead. Please find the code attached: [test2.txt](https://github.com/kind2-mc/kind2/files/2834338/test2.txt)

The stopwatchSpec has only one assumption 
`assume not (toggle and reset) ; `
and I have added these two assertions in the stopwatch node:

```
assert toggle = true -> pre( false -> pre(false ->  false)); 
assert reset = false -> pre( false -> pre(true ->  false)); 
```

I get always the following error: 'BMC Unrolling of the system is unsat at 1, the system has no more reachable states.'. Does this mean that my assumptions are inconsistent? 
Could you please help me figure out what the problem is?

**Comment by daniel-larraz** [comment]
Hi,
The equality operator (`=`) has higher precedence than the arrow operator (`->`). So you are asserting `toggle = true && reset = false` at step 0, and `false && false` at step 1. To get the expected result, enclose the expressions in parentheses:

```
assert toggle = ( true -> pre( false -> pre(false ->  false)) ); 
assert reset = ( false -> pre( false -> pre(true ->  false)) ); 
```

**Comment by anmavrid** [comment]
Thanks, works fine now.
