### ISSUE TITLE
interpreter fails with automaton 

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#561]
Hi Daniel,

Attached is the example of a lustre code contains an automaton.
I run the command 
`kind2 -xml  test3.lus  --enable interpreter --timeout 60`
I get the following error
```
 <Stream
       name="state" <Log class="fatal" source="parse">
                      Runtime error in interpreter: File "lustre/lustrePath.ml", line 1243, characters 18-24: Assertion failed
                    </Log>
```

I am only interested to check if the lustre code is correct syntactically.
Do you know of another option rather than the one I used to check a Lustre file is accepted by Kind2?
If not, is the above error can be easily fixed from your side?

Thanks,
Hamza 
[test3.txt](https://github.com/kind2-mc/kind2/files/2912837/test3.txt)

**Comment by daniel-larraz** [comment]
Hi Hamza,

The current version of the interpreter does not support Lustre code that includes automata. If you are only interested in checking if your input model is accepted by Kind 2, you can run the tool without providing any property (like in your attached model) and making sure slicing is disabled:

`kind2 --slice_nodes false test3.lus`

Hope this helps you,
Daniel

**Comment by hbourbouh** [comment]
Hi Daniel,
Thanks for answering.
The command will still look to prove properties inside the file. 
I will avoid using automaton as it appears I can use merge instead in my example.

Thanks,
Hamza
