### ISSUE TITLE
Compilation fails on 4.07.0

### ISSUE THREAD

**Issue by 5nizza** [kind2-mc/kind2#616]
The compilation fails because Ocaml does not anymore treat bytes and string the same. The error message is:

```
/home/ayrat/.opam/4.07.0/bin/ocamlopt.opt -c -w @P@U@F -annot -bin-annot -thread -color always -I utils -I testgen -I invgen -I induction -I ic3 -I qe -I smt -I c2i -I terms -I certif -I lustre -I doc -o utils/lib.cmx utils/lib.ml
File "utils/lib.ml", line 1:
Error: The implementation utils/lib.ml
       does not match the interface utils/lib.cmi:
       Values do not match:
         val string_starts_with : bytes -> bytes -> bool
       is not included in
         val string_starts_with : string -> string -> bool
       File "utils/lib.mli", line 64, characters 0-49: Expected declaration
       File "utils/lib.ml", line 583, characters 4-22: Actual declaration
```

More details from ocaml docs:

> The distinction between bytes and string was introduced in OCaml 4.02, and the "unsafe-string" compatibility mode was the default until OCaml 4.05. Starting with 4.06, the compatibility mode is opt-in; we intend to remove the option in the future.

**Comment by daniel-larraz** [comment]
The problem is [fixed](https://github.com/kind2-mc/kind2/commit/5656fc3c1368d174541fbd9a71136091b2c02c5d#diff-c0ed3023ce0251387342b6f110b8733c) in the [develop](https://github.com/kind2-mc/kind2/tree/develop) branch. Please use that version.
