### ISSUE TITLE
Parsing errors when using Interpreter with both json and csv

### ISSUE THREAD

**Issue by 5nizza** [kind2-mc/kind2#620]
hi there,

(Using release 1.1.0)

I am trying to use the interpreter module, but get parsing errors. Here are the details.

The main node inside `file.lus` is declared as

``` node NaiveSpeedometer(rev, tick: bool) returns (speed: int; update: bool);```

The input file `inputs.json` is
```
[
    { "rev": true, "tick": true },
    { "rev": true, "tick": true },
    { "rev": false, "tick": false },
    { "rev": false, "tick": false },
    { "rev": true, "tick": true }
]
```

When run
 ```
./kind2 -vvv --enable interpreter file.lus --interpreter_input_file ./inputs.json
```

I get the errors
```
<Error> State variable [ is not an input state variable

Fatal error: exception Parsing.Parse_error
Raised at file "format.ml" (inlined), line 239, characters 35-52
Called from file "format.ml", line 465, characters 8-33
Called from file "format.ml", line 480, characters 6-24
```

Am I using it wrongly, or this was fixed in the current master?

I also tried to use CSV inputs:
```
true,true
true,true
false,false
false,false
true,true
```
but got errors
```
<Error> State variable true is not an input state variable

Fatal error: exception Parsing.Parse_error
Raised at file "format.ml" (inlined), line 239, characters 35-52
Called from file "format.ml", line 465, characters 8-33
Called from file "format.ml", line 480, characters 6-24
```

(BTW: should I ask these questions in the mailing list, or here is fine?)

**Comment by daniel-larraz** [comment]
Hello,

Release 1.1.0 only supports interpreter input files in CSV format. The format is as follows: one line for each input variable of the top-level node, the first column is the name of the variable, from the second column onward you have to specify the value for the variable at step 0, 1, 2, etc. So in the case of your Lustre program the input file should contain:
```
rev,true,true,false,false,true
tick,true,true,false,false,true
```
Support for the JSON format is only available in the develop version for now, but it will be included in the new release that we plan to publish very soon.

Either channel is fine for asking questions. As a general recommendation, use this channel if you think there is a bug in Kind 2, and use the mailing list if you think other users could help you with your question.

**Comment by 5nizza** [comment]
thanks, it works in the dev version, both json and csv (but in the 1.1.0 release, inputting csv failed and showed some Not_found Execution)
