### ISSUE TITLE
Verification of liveness properties

### ISSUE THREAD

**Issue by SweeWarman** [kind2-mc/kind2#633]
Does Kind2 support verification of liveness properties? This [website](https://kind2-mc.github.io/kind2/) explicitly states Kind2 is used for safety properties. But given that SMT solvers are used, I would assume that liveness properties can be model checked as well (at least in a bounded sense), is that assumption valid?

**Comment by daniel-larraz** [comment]
Hello Swee. Thank you for your interest in Kind 2. Kind 2 does not support the verification of (arbitrary) liveness properties. It only supports the verification of _bounded_ liveness and safety properties. Please refer to [Kind 2 user documentation](https://kind.cs.uiowa.edu/kind2_user_doc/) for further details on [how to specify properties](https://kind.cs.uiowa.edu/kind2_user_doc/2_input/1_lustre.html#properties-and-top-level-node).

**Comment by daniel-larraz** [comment]
Closing this issue. Please feel to open another one if you have more questions.
