### ISSUE TITLE
In one state invariant generator (bool): a check-sat resulted in `unknown`

### ISSUE THREAD

**Issue by hbourbouh** [kind2-mc/kind2#636]
Hi Daniel,

I keep getting a warning from Kind2 failing in some state invariant generator.
I was curious what happens when you set "--check_sat_assume" to false?
Is the verification still sound? What does it change? 
Is it recommended to keep it always disabled?

Thanks,
Hamza

**Comment by daniel-larraz** [comment]
Hi Hamza,

It changes the encoding of the SMT problem sent to the solver. When the flag is true, it uses the SMTLIB command `check-sat-assuming`. When the flag is false, it uses a sequence of `push`/`pop` commands to simulate the effect of the `check-sat-assuming` command. Verification is still sound. However, when the `check-sat-assuming` is used, the SMT solver has the chance to handle the context more efficiently. This is why the flag is set to true by default. Unfortunately, we have experienced situations in which the SMT solver works fine using `push`/`pop` but it fails to solve the problem using `check-sat-assuming`. For instance, when solving certain problems that contain non-linear constraints.

Best,
Daniel

**Comment by hbourbouh** [comment]
Thanks Daniel for the quick reply.
That's my experience too, Kind2 terminates quickly when check_sat_assume is disabled. 

Best,
Hamza
