### ISSUE TITLE
Randomly but repeatably occurring unsound result

### ISSUE THREAD

**Issue by manthonyaiello** [kind2-mc/kind2#715]
I have a trivial model with a witness property (a property that I expect the model checker to falsify with a counterexample) for which I am getting random but repeatable "successful" proof. Here's the model, which is also attached as a file (with .txt added as a suffix to make github happy):

```
node model(a, b: int) returns (r : bool);
(*@contract

    var pre_a: int = 0 -> pre(a);
    var pre_b: int = 0 -> pre(b);

    assume "a increments with reset at 2"
        if pre_a = 0 then
            a = 1
        else if pre_a = 1 then
            a = 2
        else
            a = 0;

    assume "b increments with reset at 4"
        if pre_b = 0 then
            b = 1
        else if pre_b = 1 then
            b = 2
        else if pre_b = 2 then
            b = 3
        else if pre_b = 3 then
            b = 4
        else
            b = 0;
*)
let
    r = (a = 2 and b = 4);

    check "witness a = 2" not (
        a = 2
    );

    check "witness b = 4" not (
        b = 4
    );

    check "witness r" not r;
tel
```

Some of the time (I'd say a bit more than 50% of the time), the checker provides the expected counterexample:

```
<Failure> Property witness r is invalid by bounded model checking for k=13 after 0.083s.

Counterexample:
  Node model ()
    == Inputs ==
    a     1     2     0     1     2     0     1     2     0     1     2     0     1     2
    b     1     2     3     4     0     1     2     3     4     0     1     2     3     4
    == Outputs ==
    r false false false false false false false false false false false false false  true
```

But some of the time, the checker "proves" the property:

```
<Success> Property witness r is valid by inductive step after 0.084s.
```

In all cases, I also see errors:
```
<Error> Runtime failure in property directed reachability: set_prop_invariant
```
or
```
<Error> Caught exception Failure("prop_false")
```

I've attached full output for both the correct and incorrect output, below, and additionally with -vv for both cases (5 files in total).

At a guess, this is the relevant part of the -vv output in the unsound case:
```
 Message received from property directed reachability: Property witness b = 4 false at step 3

 Message received from inductive step: Property witness r invariant (4-inductive)

 Message received from bounded model checking: Property witness r false at step 13

<Success> Property witness r is valid by inductive step after 0.086s.

<Error> Caught Failure("prop_false") in invariant manager.
        Backtrace:
        Raised at Property.set_prop_false in file "src/property.ml", line 207, characters 8-36
        Called from TransSys.set_prop_status.(fun) in file "src/transSys.ml", line 1318, characters 8-32
        Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
        Called from TransSys.set_prop_status in file "src/transSys.ml", line 1315, characters 4-195
        Called from TransSys.set_prop_false in file "src/transSys.ml" (inlined), line 1336, characters 2-46
        Called from KEvent.update_trans_sys_sub.update_trans_sys' in file "src/kEvent.ml", line 1902, characters 6-45
        Called from KEvent.update_trans_sys in file "src/kEvent.ml", line 1946, characters 4-60
        Called from InvarManager.handle_events in file "src/invarManager.ml", line 38, characters 4-61
        Called from InvarManager.loop in file "src/invarManager.ml", line 187, characters 2-42
        Called from Kind2Flow.analyze in file "src/kind2Flow.ml", line 549, characters 6-82
        Called from Kind2Flow.run.loop in file "src/kind2Flow.ml", line 699, characters 8-67
        Called from Kind2Flow.run in file "src/kind2Flow.ml", line 723, characters 6-13
```
It appears that kind2 sees the property as invalidated by BMC=13 but for some reason marks the property true at K=4.

[unsound.lus.txt](https://github.com/kind2-mc/kind2/files/6043526/unsound.lus.txt)
[sound-result-vv.txt](https://github.com/kind2-mc/kind2/files/6043516/sound-result-vv.txt)
[sound-result.txt](https://github.com/kind2-mc/kind2/files/6043517/sound-result.txt)
[unsound-result-vv.txt](https://github.com/kind2-mc/kind2/files/6043518/unsound-result-vv.txt)
[unsound-result.txt](https://github.com/kind2-mc/kind2/files/6043519/unsound-result.txt)

**Comment by daniel-larraz** [comment]
Thank you very much for reporting this bug.

I can reproduce the issue. I will take a look at it soon.

Daniel

**Comment by daniel-larraz** [comment]
It seems there is a bug in the implementation of path compression for k-induction.

Until the issue is fixed, you can disable the option by passing this flag to Kind 2: `--ind_compress false`

**Comment by manthonyaiello** [comment]
@daniel-larraz thank you for the quick response. I confirm that `--ind_compress false` appears to have stabilized the issue (although absence of evidence and all that ....)

In terms of philosophy of the tool and its reporting: I note that when it declared "success" for the property, it also printed out the `<Note> Result analysis: no safe result`. Is that indicative of internal error diagnosis? that the tool detected that something went wrong and the analysis results should be considered untrustworthy?

**Comment by daniel-larraz** [comment]
@manthonyaiello wrote:
> Is that indicative of internal error diagnosis?

In fact, it is not. Kind 2 classifies the final analysis result as `SAFE` if all properties were proven valid, `UNSAFE` if some property was falsified, and `NO SAFE` otherwise. In the latter case, Kind 2 prints out the message `Result analysis: no safe result` to indicate no all properties were proven valid before termination (Kind 2 shows results incrementally, so printing this message makes easier to distinguish a situation where only some of the properties were proven valid from one where all of them were). You can check how the final analysis result was classified by looking the exit code of the program (`SAFE`: 20, `UNSAFE`: 10, `NO SAFE`: 0). In addition, Kind 2 can return an exit code 2 if an `ERROR` was detected.

Having said that, I see why the `no safe result` message can be misleading, so I will review it. Moreover, as you have noticed, Kind 2 classifies the final result for your model as `NO SAFE` (in some runs) despite some of the properties were falsified. This is due to a bad handling of the `prop_false` and `set_prop_invariant` exceptions. Kind 2 should give an `ERROR` in those cases because the `prop_false` and `set_prop_invariant` exceptions do indicate the tool detected that something went wrong. Namely, Kind 2 got two contradictory results for the same property from different verification engines. I will fix and improve the reporting of the tool too.

**Comment by manthonyaiello** [comment]
@daniel-larraz Sounds good — that would definitely help users diagnose when there is a problem.

FWIW, in case it helps in your debugging, the model below *always* results in the unsound result (at least on my machine). There's no magic here, I think: the likelihood of the unsound result appears to increase as the length of time for BMC to falsify the property increases. Here, since we're above k=20 to falsify, the tool is always declaring premature victory. :)

```
node model(a, b: int) returns (r : bool);
(*@contract

    var pre_a: int = 0 -> pre(a);
    var pre_b: int = 0 -> pre(b);

    assume "a increments with reset at 2"
        if pre_a = 0 then
            a = 1
        else if pre_a = 1 then
            a = 2
        else
            a = 0;

    assume "b increments with reset at 4"
        if pre_b = 0 then
            b = 1
        else if pre_b = 1 then
            b = 2
        else if pre_b = 2 then
            b = 3
        else if pre_b = 3 then
            b = 4
        else if pre_b = 4 then
            b = 5
        else if pre_b = 5 then
            b = 6
        else
            b = 0;
*)
let
    r = (a = 0 and b = 0);

    check "witness r" not r;
tel
```
