### ISSUE TITLE
a problem on Lustre grammar supported by Kind2

### ISSUE THREAD

**Issue by kumori123** [kind2-mc/kind2#916]
Hi, I tried to use kind2 on my own lustre code. Although I followed the rules in syntax_test.lus and decided to declare some types like
```
type sint8 = subrange [-128, 127] of int;
type uint8 = subrange [0, 255] of int;
```
but there seems to be a syntax error in line2:5, which makes me confused.
Is there anything wrong with my code?
Thank you!

**Comment by daniel-larraz** [comment]
`uint8` is a reserved word for the type of an unsigned [machine integer](https://kind.cs.uiowa.edu/kind2_user_doc/2_input/3_machine_ints.html) of width 8. I'll look if we can provide a more informative message.

**Comment by kumori123** [comment]
The issue has been resolved after I change uint8 to usint8.
Thanks!
