### ISSUE TITLE
Error with multidimensional array constructor

### ISSUE THREAD

**Issue by kumori123** [kind2-mc/kind2#951]
```
node master__Operator1 ( input1:int^3 ) returns ( output1:int^3^2 )
	var
		Edge_3:int^3;
		Edge_4:int^3^2;

	let
		Edge_3 = input1;
		Edge_4 = Edge_3 ^ 2;
		output1 = Edge_4;
		--%MAIN ;
		check output1[1][0] < 4;
	tel
```
I tried the code firstly with kind2 1.5.1, resulted in a unexpected counter example. So, I turned to kind2 1.8.0, which end up with several runtime errors. Is there anything wrong with the code above? 
Thank you in advance!

**Comment by daniel-larraz** [comment]
Thank you for reporting this issue.

There is nothing wrong with your code. The code triggers a bug in both versions of Kind 2.

Support for arrays is an experimental feature. We are considering dropping its support and replacing arrays with other high-level data structures like maps. We would appreciate it if you could provide feedback on how you use arrays and what for.

Thank you!
