### ISSUE TITLE
Issue with merge and multiple stream assignments in equation

### ISSUE THREAD

**Issue by andreaskatis** [kind2-mc/kind2#961]
```
node  A(
	__time_step : real; __nb_step : int;)
returns(
	Output_1 : bool; Output_2 : bool;);
let
	Output_1 = true;
	Output_2 = false;
tel

node  B(
	_isEnabled : bool; __time_step : real; __nb_step : int;)
returns(
	Output_1 : bool; Output_2 : bool;);
var 
	pre_Output_1 : bool; pre_Output_2 : bool;
let
	pre_Output_1 = false;
	pre_Output_2 = false;
	(Output_1, Output_2) = merge(_isEnabled;
	(activate A every _isEnabled)(__time_step, __nb_step);
	(pre_Output_1, pre_Output_2) when not(_isEnabled));	
tel
```

The syntax check fails for the example code above with the following message:

`Width lengths of equation are not equal`

I encountered the above using versions v1.5.1 , 1.7.0 and 1.8.0 (web interface). The latest version I know where this was not a problem is v1.2.0 .

**Comment by daniel-larraz** [comment]
Hi Andreas,

Thank you for reporting this issue. It is a bug in the new front-end.

I created a PR #962 that fixes this issue.

Thanks,
Daniel
