### ISSUE TITLE
Kind2 exits with code 40 for unrealizable contracts

### ISSUE THREAD

**Issue by andreaskatis** [kind2-mc/kind2#982]
I am not sure if this was intended, but it causes issues when calling kind2 via the exec command in NodeJS, which flags any non-zero exit code as an error.

This was noticed with Kind 2 v1.9.0

The exit code for realizable contracts is still 0, as previously.

To reproduce, use the attached contract: [FSM_cc0.lus.txt](https://github.com/kind2-mc/kind2/files/11557347/FSM_cc0.lus.txt)

I ran the following commands in Linux:

`kind2 -json --enable CONTRACTCK --timeout 900 FSM_cc0.lus
`
` echo $?  -> this returns the exit code of the last command
`

**Comment by daniel-larraz** [comment]
Hi Andreas. Yes, this was intended. You can find a description of the exit code convention here:
https://kind.cs.uiowa.edu/kind2_user_doc/3_output/3_exit_codes.html

**Comment by andreaskatis** [comment]
Thank you, Daniel!

**Comment by daniel-larraz** [comment]
Hi Andreas. In case it helps, I just added an [option](https://github.com/kind2-mc/kind2/pull/983) to Kind 2 (`--exit_code_mode only_errors`) that allows you to get back the old behavior. Cheers.

**Comment by andreaskatis** [comment]
Hi Daniel,

I already implemented a way to handle the new behavior. I suppose the new option cannot be added to the current release (v.1.9.0), correct? If that is possible, I may look into using it. If not, it will probably not be as useful for me, since it may be the case that FRET/CoCosim users will download v1.9.0.

In any case, thank you for your help so far!

**Comment by daniel-larraz** [comment]
I'm afraid not. Sorry for the inconvenience.
